version: "3.9"

secrets:
  PUBLIC_SWARMPIT_SSH:
    external: true

services:
  nodeapp:
    build:
      context: .
      args:
        SSH_PRIVATE_KEY: PUBLIC_SWARMPIT_SSH
    ports:
      - "6000:6000"
    environment:
      - PRIVATE_SSH=/run/secrets/PUBLIC_SWARMPIT_SSH
