version: "3.9"

secrets:
  PRIVATE_SWARMPIT_SSH:
    external: true
  PUBLIC_SWARMPIT_SSH:
    external: true

services:
  nodeapp:
    build:
      context: .
      args:
        SSH_PRIVATE_KEY: PRIVATE_SSH
        SSH_PUBLIC_KEY: PUBLIC_SSH
    ports:
      - "6000:6000"
    environment:
      - PRIVATE_SSH=/run/secrets/PRIVATE_SWARMPIT_SSH
      - PUBLIC_SSH=/run/secrets/PUBLIC_SWARMPIT_SSH
