name: Audit

on:
  push:
    branches: [stage, dev]
  pull_request:
    branches: [stage, dev]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: /srv/backend/proxy.sh