name: Docker Image CI

on:
  push:
    branches: [ stage ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/proxy:latest .

      - name: Log in to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push tag to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/proxy:latest
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: /root/other/deploy_from_dockerhub.sh