name: dev
on:
  push:
    branches:
      - dev

jobs:
  dev:
    name: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: werf/actions/install@v2

      - run: |
          ip a
          docker login dev.docker.registry.msanalytics.ru:4443 -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          werf converge
        env:
          WERF_REPO: dev.docker.registry.msanalytics.ru:4443
          WERF_ENV: dev
          WERF_KUBECONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}