name: dev
on:
  push:
    branches:
      - dev

jobs:
  dev:
    name: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: werf/actions/install@v2

      - run: |
          export WERF_REPO="https://dev.docker.registry.msanalytics.ru:4443"
          werf converge
        env:
          WERF_ENV: dev
          WERF_KUBECONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}