name: dev
on:
  push:
    branches:
      - dev

jobs:
  dev:
    name: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: werf/actions/install@v2

      - run: |
          echo "${{ secrets.DOMAIN_DOCKER_REGISTER_CRT }}" > domain.crt
          sudo cp domain.crt /usr/local/share/ca-certificates/dev.docker.registry.msanalytics.ru.crt
          sudo update-ca-certificates
          sudo systemctl restart docker

          docker login dev.docker.registry.msanalytics.ru:4443 -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

          # Проверка наличия образа в Docker Registry
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X GET "https://dev.docker.registry.msanalytics.ru:4443/v2/myrepository/manifests/latest")

          # Если образ не найден, выполняем сборку
          if [ "$HTTP_STATUS" -eq 404 ]; then
            echo "Образ не найден. Выполняем сборку..."
            
            # Сборка и отправка Docker-образа
            docker build -t dev.docker.registry.msanalytics.ru:4443/myrepository:latest .
            docker push dev.docker.registry.msanalytics.ru:4443/myrepository:latest
            
            echo "Сборка и отправка образа завершены."
          else
            echo "Образ найден в Docker Registry. Сборка не требуется."
          fi

          werf converge
        env:
          WERF_REPO: dev.docker.registry.msanalytics.ru:4443
          WERF_ENV: dev
          WERF_KUBECONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}